# Generated by Django 4.1.5 on 2024-08-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('savingtime', models.FloatField()),
                ('size', models.IntegerField()),
            ],
        ),
    ]
